apiVersion: v1
kind: Namespace
metadata:
  name: secure-namespace
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: privileged-pod
  name: privileged-pod
  namespace: secure-namespace
spec:
  containers:
  - image: nginx
    name: privileged-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
