apiVersion: v1
kind: Namespace
metadata:
  name: secure-namespace
---
# Should be rejected
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: privileged-pod
  name: privileged-pod
  namespace: secure-namespace
spec:
  containers:
  - image: nginx
    name: privileged-pod
    resources: {}
    securityContext:
      privileged: true
      allowPrivilegeEscalation: true
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
# Should be accepted but mutated
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: non-root-pod
  name: non-root-pod
  namespace: secure-namespace
spec:
  containers:
  - image: nginx
    name: non-root-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
# Should be accepted but mutated, but keep the runAsUser
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: non-root-pod-2
  name: non-root-pod-2
  namespace: secure-namespace
spec:
  securityContext:
    runAsUser: 65000
  containers:
  - image: nginx
    name: non-root-pod
    resources: 
      limits:
        cpu: 102m
        memory: 130Mi
      requests:
        cpu: 101m
        memory: 129Mi
    securityContext:
      runAsUser: 65000
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
# Should be denied
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: root-pod
  name: root-pod
  namespace: secure-namespace
spec:
  securityContext:
    runAsUser: 0
  containers:
  - image: nginx
    name: root-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
